### ISSUE TITLE
Flutter flavors talk

### ISSUE THREAD

**Issue by enzoftware** [FlutterPeru/propuestas-meetup#1]
[My slides for the talk]( https://docs.google.com/presentation/d/1_9NDoNTUqPqX-mhPvUVXMRT1_gH3mXx27LRwHKCGA7w/edit?usp=sharing)

**Comment by diegoveloper** [comment]
Hola Enzo,
Posible Fecha seleccionada: 14 de agosto de 7 a 9pm , Lugar: San Isidro av. Víctor Andrés Belaúnde 147, torre real 2 (wework). 

Confirmas asistencia?

**Comment by enzoftware** [comment]
Confirmado
